export const api_collection: any = {
  REGISTER_API: 'auth/register/',
  LOGIN_API: 'auth/login/',
  PROFILE_API: 'auth/profile/',
  PROFILE_UPDATE_API: 'auth/update/profile/',
  LAW_LIST_API: 'law/',
  SLIDER_API: 'home/slider/',
  HELP_CENTER_RULES_API: 'help-center/',
  KNOW_YOUR_LAW_API: 'kyl/',
  GLOBAL_SEARCH_API: 'global-search/',
  TEAM_API: 'team/',
  EVENT_API: 'event/',
  ZONE_API: 'address/',
  PAYMENT_PLANS_API: 'payment/plans/',
  PAYMENT_METHOD_API: 'payment/methods/',
  CURRENT_PAYMENT_PLAN_API: 'payment/summary/',
  PAYMENT_SUBMIT_API: 'payment/add/',
  APPOINTMENT_API: 'appointment/',
  LAWYER_LIST_API: 'lawyer/',
  APPOINTMENT_LIST_API: 'lawyer-panel/appointments/',
  APPOINTMENT_STATUS_CHANGE_API: 'lawyer-panel/appointment-status-change/',
};
